version: '3.3'
services:
    run:
        container_name: sequelize_migrations
        environment:
            - MYSQL_DATABASE=sequelize_migrations
            - MYSQL_ROOT_PASSWORD=secret
        ports:
            - '3315:3306'
        image: mysql:latest